### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by gadgetfather**
- user can login 
- user can logout
- user can signup (create new account)

# Preview 
auth

### CODE REVIEW

**Review by BISINIGISHIVANI — APPROVED** [review]
functionality working as intended.
nice ui of Login form. @gadgetfather

**Review by Ayushi20-19 — APPROVED** [review]
- UI is nice, code is good
- login, signup and logout are working fine
- one suggestion can the toast position be changed... it might be not very pleasant coming from the top

**Review by lomesshh — APPROVED** [review]
clean and modular code
UI looks good
all functionalities are working as expected
looks good to merge

**Comment by gadgetfather** [comment]
> 

Sure will work on that

**Pull request merged**
